export enum RoutePath {
  ADMIN_USER = "/admin_user",
  BANNER = "/banner",
  CONFIG = "/config",
  DASHBOARD = "/dashboard",
  DEPOSIT_FEE = "/deposit_fee",
  IDENTIFICATION = "/identification",
  LOGOUT = "/logout",
  LOGIN = "/login",
  PRODUCT = "/product",
  PRODUCT_CATEGORY = "/product_category",
  PRODUCT_BRAND = "/product_brand",
  PROMO_CODE = "/promo_code",
  SPECIAL_CATEGORY = "/special_category",
  SPECIAL_CATEGORY_LIST = "/special_category_list",
  TOP_UP = "/top_up",
  USER = "/user",
  WITHDRAW_REQUEST = "/withdraw_request",
  WILDCARD = "*"
}
